M48
; DRILL file {KiCad 9.0.6} date 2025-12-01T09:05:10-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-01T09:05:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.450
%
G90
G05
T1
X81.0Y-147.5
X81.5Y-53.5
X164.0Y-54.0
X166.0Y-147.0
T2
X87.37Y-129.5
T3
X112.72Y-54.5
X112.72Y-101.45
X137.23Y-54.5
X137.23Y-101.45
T4
X95.88Y-145.5
X151.12Y-129.5
M30
